### ISSUE TITLE
Баг с переводом в боевой режим

### ISSUE THREAD

**Issue by PushingUp** [loveorigami/yupe-sberbank-module#1]
Сейчас при переводе в боевой режим платежей из тестового меняется адрес сервера с https://3dsec.sberbank.ru на  https://securepayments.sberbank.ru 

В файле components/Sberbank.php на 49 строке зашит адрес 3dsec.sberbank.ru, поэтому при переводе на боевой режим оплата перестает работать.

**Comment by loveorigami** [comment]
Я давно им не пользовался. Тогда, когда делал, мне достаточно было поменять login и пароль. Url оставался прежним.
Напишите, как правильнее сейчас сделать. 

Настройки мерчанта не подходят для этого?

**Comment by PushingUp** [comment]
В настройках адрес мерчанта тоже меняется, но здесь адрес сервера зашит непосредственно в коде. Вот что сейчас пишет Сбербанк для перевода в боевой режим:

> Для переключения в  боевой режим Вам необходимо:
> 1. Изменить пароли для API и оператора. Затем прописать измененные авторизационные данные в Вашей системе.
> 2. Изменить адрес сервера для запросов с  https://3dsec.sberbank.ru на  https://securepayments.sberbank.ru

Поэтому для боевого режима должно быть так:

```
    public function getUrl($method)
    {
        return 'https://securepayments.sberbank.ru/payment/rest/' . $method;
    }
```

А для тестового по-старому:

```
    public function getUrl($method)
    {
        return 'https://3dsec.sberbank.ru/payment/rest/' . $method;
    }
```

Поэтому в настройках желательно добавить опцию выбора сервера, либо выдирать сервер непосредственно из адреса мерчанта.

**Comment by loveorigami** [comment]
сделал через настройку server - попробуйте

**Comment by PushingUp** [comment]
Да, все в порядке. Спасибо!
